### PR TITLE
Feature/balancing analysis

### PR DESCRIPTION
**Pull request by jdomkline**
Adjusted grouping and facet to focus on portfolio also added command arg options
Screenshot 2024-04-30 at 11 29 53 AM

### CODE REVIEW

**Comment by jdomkline** [comment]
Now with command line args to open the config for ranges, etc, also flipped grouping and facets.  @wichtounet it is up to you where you want to take this.  I raised the PR just to get you the artifact most easily.  This version is more configurable but I plan to make at least a dozen other scripts for myself.  I can share those if you want later and maybe a PR is not the best way.  Please share your thoughts.

**Comment by jdomkline** [comment]
**balancing_analysis.py localhost 8085 us_inflation 1000 30 4.0 1930 2010 5**   

Is an interesting result, confirming what I usually read.  There is no good answer to how to balance :).

**Comment by wichtounet** [comment]
Hi

It would be good to include this here for maximum exposure, but if you are going to include a dozen of scripts, it's probably not the best. Could you make one major script like I did, with options to select the feature?

**Comment by jdomkline** [comment]
Hello,

Agreed... but I may now choose another course of action.  This simulator has been so inspirational and the data you have curated is an easily overlooked gem.  I have become fascinated by the terminal values, some seem so unreal.  I have debugged through and I don't question their validity.  

I think I'm going to compliment this fantastic simulator with something else, I will take the data and at least the SWR sim and port it to python.  Once there I can bring together so much more tech owing to all the incredible Python libs.  I know you favor cpp and perf, but the trade off for more functions and math at the fingertips is too much to ignore.  An ML model running on a T/GPU (google colab) with advanced vectorized math could be very snappy. 

I'm not sure if this is something for exposure, ML is easy not to trust but fine to mess with as a hobbyist.  Again the data you have curated makes this effort worth it.  It would be cool to see how close an ML model can come to predicting the actual results from this FIRE sim.  Big companies probably have these sims many times over :).  

I'm not FIRE by the way, I'm FINE, Financial Independence **Next Endeavor**... who can give up working in and around what you love too early? 

All the best Baptiste

**Pull request closed without merging**
